#	SPDX-License-Identifier: MPL-2.0
#	xueziloader
#	platform/foreverpi/Makefile
#	Copyright (C) 2026 Yao Zi <me@ziyao.cc>

BOARD_NAME = foreverpi
include platform/ls2k0300/Makefile

OBJS	+= platform/foreverpi/late.o
